server:
  port: 8080
spring:
  application:
    name: "ScaffoldFicohsa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# Ficohsa Logging Configuration
ficohsa:
  logging:
    format: JSON
    mask-confidential: true
    record-type: U
    log-group: scaffoldLogs
    environment: DEV
    aop:
      enabled: true
    dynamodb:
      enabled: false

logging:
  level:
    co.com.ficohsa.logging: DEBUG

